#!/usr/bin/env bash
# Interactive setup: model URL / model id / optional API key → sidecar.env, then start.
set -euo pipefail

ROOT="${ZHC_FABRIC_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
STATE_DIR="${HERMES_HOME:-$HOME/.hermes}/zhc-fabric"
ENV_FILE="$STATE_DIR/sidecar.env"
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR" 2>/dev/null || true

# shellcheck disable=SC1091
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck source=/dev/null
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

# Prefer fabric-prefixed names, then classic DEFAULT_*
cur_url="${ZHC_FABRIC_DEFAULT_BASE_URL:-${DEFAULT_BASE_URL:-}}"
cur_model="${ZHC_FABRIC_DEFAULT_MODEL:-${DEFAULT_MODEL:-}}"
cur_key="${ZHC_FABRIC_DEFAULT_API_KEY:-${DEFAULT_API_KEY:-}}"
cur_inflight="${MAX_INFLIGHT_COMPLETIONS:-2}"

echo "=== zhc-fabric setup ==="
echo "Config file: $ENV_FILE"
echo "Votes need any OpenAI-compatible /v1 chat.completions endpoint."
echo "Examples:"
echo "  Ollama:     http://127.0.0.1:11434/v1   model=llama3.2"
echo "  llama.cpp:  http://127.0.0.1:8000/v1    model=<your-model-id>"
echo "  OpenRouter: https://openrouter.ai/api/v1 model=openai/gpt-4o-mini + API key"
echo

prompt() {
  local label="$1" default="$2" secret="${3:-0}" value=""
  if [[ -n "$default" && "$secret" != "1" ]]; then
    printf "%s [%s]: " "$label" "$default"
  elif [[ -n "$default" && "$secret" == "1" ]]; then
    printf "%s [set — Enter to keep, '-' to clear]: " "$label"
  else
    printf "%s: " "$label"
  fi
  if [[ "$secret" == "1" ]]; then
    # shellcheck disable=SC2162
    read -r -s value || true
    echo
  else
    # shellcheck disable=SC2162
    read -r value || true
  fi
  if [[ -z "$value" ]]; then
    printf '%s' "$default"
    return
  fi
  if [[ "$secret" == "1" && "$value" == "-" ]]; then
    printf ''
    return
  fi
  printf '%s' "$value"
}

new_url="$(prompt "Base URL (…/v1)" "$cur_url")"
new_model="$(prompt "Model id" "$cur_model")"
new_key="$(prompt "API key (optional)" "$cur_key" 1)"
new_inflight="$(prompt "Max concurrent LLM calls" "$cur_inflight")"

if [[ -z "$new_url" || -z "$new_model" ]]; then
  echo "error: base URL and model id are required." >&2
  echo "Re-run this script or set ZHC_FABRIC_DEFAULT_BASE_URL / ZHC_FABRIC_DEFAULT_MODEL." >&2
  exit 1
fi

# Normalize trailing slash
new_url="${new_url%/}"

umask 077
cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — do not commit.
# Also honored: ZHC_FABRIC_* from ~/.hermes/.env (hermes plugins install).
ZHC_FABRIC_DEFAULT_BASE_URL=$new_url
ZHC_FABRIC_DEFAULT_MODEL=$new_model
ZHC_FABRIC_DEFAULT_API_KEY=$new_key
DEFAULT_BASE_URL=$new_url
DEFAULT_MODEL=$new_model
DEFAULT_API_KEY=$new_key
MAX_INFLIGHT_COMPLETIONS=$new_inflight
EOF
chmod 600 "$ENV_FILE"

# Non-secret summary for status tooling
cat >"$STATE_DIR/config.json" <<EOF
{
  "url": "http://127.0.0.1:7733",
  "default_base_url": $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$new_url"),
  "default_model": $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$new_model"),
  "has_api_key": $([[ -n "$new_key" ]] && echo true || echo false)
}
EOF
chmod 600 "$STATE_DIR/config.json" 2>/dev/null || true

echo
echo "Wrote $ENV_FILE"
echo "  base_url=$new_url"
echo "  model=$new_model"
echo "  api_key=$([[ -n "$new_key" ]] && echo '(set)' || echo '(empty)')"
echo

# Sync into Hermes .env so `hermes plugins install` skips re-prompts later
if [[ -d "${HERMES_HOME:-$HOME/.hermes}" ]]; then
  python3 - <<PY
from pathlib import Path
import os, re
env_path = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes")) / ".env"
pairs = {
    "ZHC_FABRIC_DEFAULT_BASE_URL": """${new_url}""",
    "ZHC_FABRIC_DEFAULT_MODEL": """${new_model}""",
    "ZHC_FABRIC_DEFAULT_API_KEY": """${new_key}""",
}
text = env_path.read_text(encoding="utf-8") if env_path.is_file() else ""
for k, v in pairs.items():
    line = f"{k}={v}"
    pat = re.compile(rf"(?m)^{re.escape(k)}=.*$")
    if pat.search(text):
        text = pat.sub(line, text)
    else:
        if text and not text.endswith("\n"):
            text += "\n"
        text += line + "\n"
env_path.parent.mkdir(parents=True, exist_ok=True)
env_path.write_text(text, encoding="utf-8")
try:
    env_path.chmod(0o600)
except OSError:
    pass
print(f"Synced ZHC_FABRIC_DEFAULT_* into {env_path}")
PY
fi

echo "Starting sidecar..."
bash "$ROOT/scripts/install-sidecar.sh" restart

echo
echo "Done. In Hermes: /fabric status   (restart gateway if tools are missing)"
echo "Smoke: $ROOT/scripts/smoke.sh"
